### ISSUE TITLE
Endpoint 'productPricing', operation 'getCompetitivePricing' does not work correctly with Asins

### ISSUE THREAD

**Issue by altruer** [amz-tools/amazon-sp-api#143]
When you add query parameters

>     ItemType: 'Asin',
>     Asins: ['B00WII52ZU', 'B08T68JQNP'],
> 

You get

> [
>   {
>     "ASIN": "B00WII52ZU, B08T68JQNP",
>     "status": "ClientError"
>   }
> ]

Problem is that lib does twice encoding (what is got from /amazon-sp-api/lib/resources/versions/product_pricing/productPricing_v0.js)

Single encoding is enough here
So I propose to remove `encode_twice:true` for this endpoint

Please check how it will behave with SKU array

Thanks!

**Comment by colin-brown** [comment]
We get the same problem when submitting an array of Asins. Setting encode_twice:false fixes for us. As per OP unsure whether special characters in SKU might cause a problem with encode_twice:false?

**Comment by amz-tools** [comment]
Hi @altruer, @colin-brown,

we fixed the issue. The reason was actually that because of the necessary double encoding for skus with special chars for the two operations `getPricing` and `getCompetitivePricing`, the array delimiter `,` was also encoded twice, resulting in Amazon not being able to split up the array. Thats why the two ASINs were not received as two separate array values but as one: `"ASIN": "B00WII52ZU, B08T68JQNP"`.

What still persists now is the issue of Amazon splitting up an array value containing a `,` into two values when part of the query. There's no real fix for it yet, but the[ issue is already communicated to Amazon](https://github.com/amzn/selling-partner-api-docs/issues/2374).

**Comment by altruer** [comment]
Thank you very much, works as expected now!

**Comment by wangjue666** [comment]
Thanks a million！
