### ISSUE TITLE
Invalid or unsupported document ID found

### ISSUE THREAD

**Issue by luislovera87** [amz-tools/amazon-sp-api#150]
Unable to create RDT for restricted resource: 
path: `/reports/2020-09-04/reports` 
method: `GET`
`"amazon-sp-api": "0.7.9"`
Error: `{"code":"InvalidInput","message":"Invalid or unsupported document ID found","details":"","type":"error"}`

<img width="655" alt="Screen Shot 2022-07-21 at 11 06 57 PM" src="https://user-images.githubusercontent.com/97060430/180360522-234a03c9-61b6-49c5-abf7-c0cfe0ef4888.png">

<img width="969" alt="Screen Shot 2022-07-21 at 11 09 04 PM" src="https://user-images.githubusercontent.com/97060430/180360668-296624cc-3802-4d0c-983d-abe6d04e7640.png">

**Comment by amz-tools** [comment]
Hi @luislovera87,

it looks like your path is wrong. Take a look at the [tokens API use case guide](https://developer-docs.amazon.com/sp-api/docs/tokens-api-use-case-guide#restricted-operations). The restricted path is actually `getReportDocument`, so you will have to request the RDT with the path of the `getReportDocument` call: 

`/reports/2020-09-04/documents/{reportDocumentId}`

So first you would have to call the `createReport` and the `getReport` operations in order to retrieve a `reportDocumentId`, which you then can use to get the RDT, use that for the `getReportDocument` request and download the report.

**Comment by luislovera87** [comment]
HI @amz-tools ,
thanks for the detailed explanation. Although, I've been trying to retrieve the `GET_FLAT_FILE_ORDER_REPORT_DATA_TAX` report which is part of the [Restricted report types](https://developer-docs.amazon.com/sp-api/docs/tokens-api-use-case-guide#restricted-operations). 


<img width="797" alt="Screen Shot 2022-07-25 at 9 34 26 PM" src="https://user-images.githubusercontent.com/22124020/180910662-96905ba4-3dd7-425f-adc0-fde3ed0caab5.png">

I enabled the role to my app (see screenshot).

<img width="797" alt="Screen Shot 2022-07-25 at 9 35 41 PM" src="https://user-images.githubusercontent.com/22124020/180910885-d8620cc6-703c-4f48-abfb-8e544ec2eddd.png">

That is the reason, why I tried creating a RDT to retrieve the report but I'm getting the error mentioned on my first post.

**Comment by amz-tools** [comment]
Maybe you could try it with the new report endpoint version (2021-06-30) and see if that works better?

**Comment by luislovera87** [comment]
Changing the version didn't work as well. 

Will contact amazon directly but thanks for the help.
