### ISSUE TITLE
CustomError: SKU 'Peak%20Biome_BowelGuard' not found in marketplace ATVPDKIKX0DER

### ISSUE THREAD

**Issue by SWengineer-A** [amz-tools/amazon-sp-api#176]
Hello, @amz-tools 

We are getting custom error: "CustomError: SKU 'Peak%20Biome_BowelGuard' not found in marketplace", when calling
`getlistingsitem` for seller_sku having space.

The correct sku in amazon is 'Peak Biome_BowelGuard', seems like an issue while encoding/decoding for url. 

Could you check it, please?

**Comment by SWengineer-A** [comment]
Is there any update for this issue?

**Comment by amz-tools** [comment]
@SWengineer-A Sorry, kind of missed this one. We will have a look at it by latest tomorrow. Just to make sure: You are using the current 0.8.0 version?

**Comment by SWengineer-A** [comment]
thanks for your quick reply. @amz-tools 

yes, i am using 0.8.0 now. 

Looking forward to hearing from you soon.

**Comment by amz-tools** [comment]
Hi @SWengineer-A,

we just checked and it works fine for us. As we don't have an SKU by the name we receive the error "CustomError: SKU 'Peak Biome_BowelGuard' not found in marketplace" as it should be (with empty space instead of %20). Could you post your request here so we can check what might be the problem?

**Comment by SWengineer-A** [comment]
Hi, @amz-tools 
As I clean the npm cache and re-install , issue was resolved. 
thanks for your time and consideration. 
Regards.
