### ISSUE TITLE
message: 'Access to requested resource is denied.', been at this for over a week...

### ISSUE THREAD

**Issue by born2net** [amz-tools/amazon-sp-api#194]
keep getting same error over:

```
{ CustomError: Access to requested resource is denied.
    at SellingPartner.callAPI (/tmp/abc/node_modules/amazon-sp-api/lib/SellingPartner.js:705:13)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
  message: 'Access to requested resource is denied.',
  code: 'Unauthorized',
  details: '',
  type: 'error' }
```
I have tried every possible config ARN / user / role, STS permissions 
creating app with role, with user... with every possible config.
I am out of ideas.

:/

Sean

**Comment by unitario** [comment]
Getting the same error. Have provided correct credentials.

**Comment by born2net** [comment]
eventually after so many trial and errors it worked.
try this end point first as it seems least secure:

```
await sellingPartner.refreshAccessToken();
    await sellingPartner.refreshRoleCredentials();
    let access_token = sellingPartner.access_token;
    let role_credentials = sellingPartner.role_credentials;
    let res = await sellingPartner.callAPI({
        operation: 'getMarketplaceParticipations',
        endpoint: 'sellers'
    });
```
once that's working you can figure out the cmd u need.

**Comment by unitario** [comment]
@born2net Thanks positing a solution. Found a lot of people with similar issues and no solution. Can you post some more of your code, it is not clear how you are providing `access_token` and `role_credentials`?

**Comment by born2net** [comment]
honestly I cant tell why it started working all of a sudden, I tried all the same combinations people always post about IAM, user role etc. I almost feel it just takes amazon like a week before they allow the API calls through.

**Comment by unitario** [comment]
Ok, thanks anyway.

In our case we are using the Vendor Central and it seems that our account only have access to a limited range of endpoints. For example when I was trying to access `orders` it didn't work but when I tried to access `feeds` it worked fine.

Of course in true Amazon fashion, this is not documented anywhere, nor will you get any useful information back from the API to deduct what the issue might be.

I suggest to anyone that is running into this issue is to investigate role permissions to specific resources in the Selling Partner API. If I find any useful documentation I will make sure to post it in here.
