### ISSUE TITLE
getReports doesn't seem to understand a lot of reportTypes, causes schema errors 

### ISSUE THREAD

**Issue by ericblade** [amz-tools/amazon-sp-api#222]
I'm just trying to assemble a list of actually working reportTypes that can be passed to getReports, since it's not as functional as it used to be in MWS... 

and...

```
    // 'GET_PAN_EU_OFFER_STATUS', // Spain, UK, France, Germany, Italy only?
    // 'GET_MFN_PANEU_OFFER_STATUS', // Spain, UK, France, Germany, Italy only?
    // Settlement Reports - see https://developer-docs.amazon.com/sp-api/docs/report-type-values-settlement
    // 'GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE', // Invalid?!
    // 'GET_V2_SETTLEMENT_REPORT_DATA_XML', // Invalid?!
    // 'GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2', // Invalid?!
    // Order Reports - see https://developer-docs.amazon.com/sp-api/docs/report-type-values-order
    // 'GET_FLAT_FILE_ACTIONABLE_ORDER_DATA_SHIPPING',
    // 'GET_ORDER_REPORT_DATA_INVOICING',
    // 'GET_ORDER_REPORT_DATA_TAX',
```
all of these order types fail with

```
CustomError: One or more parameters does not conform to the schema constraints.
    at SellingPartner.callAPI (C:\src\finder\node_modules\amazon-sp-api\lib\SellingPartner.js:659:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)       
    at async Object.find (C:\src\finder\src\services\amazon-report\amazon-report.class.js:55:32) {
  code: 'InvalidInput',
  details: 'reportTypes;',
  type: 'error'
}
```
i am not seeing where in the source code any of this is, so, not sure how to go about fixing it

This is likely nowhere near a comprehensive list, the new reportTypes list is immense and scattered across *20* pages of documentation, and so it could take me quite a while to go through if i have to do it line by line

**Comment by amz-tools** [comment]
@ericblade Nice to idea to have a comprehensive list of all report types! Maybe I can help a bit here:

Concerning the PAN-EU offer status reports: You are right, its just these 5 countries.

Concerning the settlement reports: Maybe you are using the old (2020-09-04) version of the report instead of the new (2021-06-30) version and these reports are not available for the old version?

Concerning the order reports you mentioned: These are restricted by Amazon, you can only request these if you have the restricted role "Tax invoicing".

**Comment by ericblade** [comment]
Hi! Thanks for the response.  

Can you confirm if the 2021-06-30 version has a larger list of report types available than the 2020-09-04 version?  I was trying to find somewhere in the source where it validates any of this, and I couldn't find anything.  

The schema constraints error is an issue, though, I think, unless I completely fail to understand what's going on.  The schema constraints error appears to be coming from this library, rather than from Amazon.  I don't think the library would be able to understand that I do or do not have access to those reports.  Am I wrong there?    

I definitely need a list of reports that are available, so I can pass the list along, or I get to completely redesign the reports view functionality in my app in a user-hostile method, because Amazon is not allowing us to query "give a list of any kind of report" as it used to do with MWS. :D  It's forcing the user to specify which report they want to request/review.   Which also means that the l ist of reports that can be requested are different from the list of reports that can be viewed, because there are several reports that can be viewed but only Amazon can create.

The reports system is a worse mess than most of the rest of the API, and the rest of the API is an awful mess.

**Comment by amz-tools** [comment]
I can't really confirm that 2021-06-30 has more reports available, but its just a matter of testing each report against the two endpoints and see if the new one returns a valid answer whereas the old one doesn't.

But I can confirm that the error message you see definitely comes from Amazon and not from the library.

I agree that the reports section is quite complicated due to the nature of so many different reports, but at least Amazon has now finally provided a list of the [returned attributes for each report](https://developer-docs.amazon.com/sp-api/docs/reports-attributes). Its definitely not the best and most well documented API, but compared to MWS I would say its a big step forward.

**Comment by ericblade** [comment]
ok, thank you for confirming then that this library is not doing the validation, and that it's Amazon actively refusing it.  I couldn't find the validation code because it isn't there :-D 

so, this isn't a problem with this software, we can close it, but while I do have your attention real quick :) can you tell me if this is the correct way to setup, with the latest version of that API?

```
new SellingPartnerAPI({
        region: 'na',
        refresh_token: res.refresh_token,
        endpoints_versions: {
            reports: '2021-06-30',
        },
        credentials: {
            SELLING_PARTNER_APP_CLIENT_ID,
            SELLING_PARTNER_APP_CLIENT_SECRET,
            AWS_SECRET_ACCESS_KEY,
            AWS_ACCESS_KEY_ID,
            AWS_SELLING_PARTNER_ROLE,
        },
    });
```

**Comment by amz-tools** [comment]
@ericblade Yes, the config looks fine to me.
