### ISSUE TITLE
Error uploading feed with document: SignatureDoesNotMatch

### ISSUE THREAD

**Issue by fehnd** [amz-tools/amazon-sp-api#23]
Hi!

When i try to use the upload method after the use of the "createFeedDocument" i have a problem signing the request, i',m using the information recovered from the previous call, and this for the feed:

```
let feed = {    
    content:"<?xml version=\"1.0\" ?></xml>",
    contentType:'text/xml; charset=utf-8'
}
```

This throws the following error:

```
CustomError: The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

Somebody can help me with this? i don't know why doesn't work,

Below i paste the code used for testing the functionality:

```
(async() => {
        try {   
        let sellingPartner = await new SellingPartnerAPI({        
            region:'eu', // The region of the selling partner API endpoint ("eu", "na" or "fe")        
            refresh_token:process.env.REFRESH_TOKEN // The refresh token of your app user      
        });  
        console.log(sellingPartner._credentials)      
        let feed_upload_details = await sellingPartner.callAPI({    
            operation:'createFeedDocument',    
            body:{      
                contentType:'text/xml; charset=UTF-8'    
            }  
        });

        console.log(feed_upload_details);
        let res = await sellingPartner.upload(feed_upload_details, feed);

        console.log(feed_upload_details);  
        console.log(feed_creation_infos); 
         
    } catch(e){      
        console.log(e);    
    }  
```

**Comment by amz-tools** [comment]
Hi @fehnd,

I think the problem is the content-type. Its part of the signature so it must be identical for the .upload function and the createFeedDocument operation. You are using 'text/xml; charset=UTF-8'  (UTF-8 as uppercase) for the createFeedDocument operation and  'text/xml; charset=utf-8' (utf-8 as lowercase) for the feed you are using with the .upload function.

You would have to use the exactly identical content-type string for both, so either 'text/xml; charset=UTF-8' or 'text/xml; charset=utf-8'.

Hope this helps!

**Comment by fehnd** [comment]
hi @amz-tools 

That's right, this was the problem, i set the same string for both and it's working.

Thanks a lot!
