### ISSUE TITLE
Example for POST_ORDER_FULFILLMENT_DATA

### ISSUE THREAD

**Issue by unterweltler** [amz-tools/amazon-sp-api#24]
Someone successful using the `POST_ORDER_FULFILLMENT_DATA` feed to update the Order Status to `shipped`?

Can please someone provide an example of the Feed XML?
Also can I update more than one Order with this Feed?
Because there is also the `POST_FLAT_FILE_FULFILLMENT_DATA` Feed ...

Currently I'm testing with this Feed XML

```xml
<?xml version="1.0" encoding="utf-8"?>
<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
    <Header>
        <DocumentVersion>1.02</DocumentVersion>
        <MerchantIdentifier>XXX</MerchantIdentifier>
    </Header>
    <MessageType>OrderFulfillment</MessageType>
    <Message>
        <MessageID>1</MessageID>
        <OrderFulfillment>
            <AmazonOrderID>XXX-XXXXXX-XXXXXX</AmazonOrderID>
            <FulfillmentDate>2021-02-28T12:34:56</FulfillmentDate>
        </OrderFulfillment>
    </Message>
</AmazonEnvelope>
```

but I'm not sure if it's correct like that ... I used the [Schema](https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/OrderFulfillment.xsd) and tried to reproduce the given example in the Docs.

---

Also, can I see any details of a Feed Report?
I'm getting:

```
{
  processingEndTime: '2021-02-28T12:14:49+00:00',
  processingStatus: 'DONE',
  marketplaceIds: [ 'A1PA6795UKMFR9' ],
  feedId: 'XXXXXXXX',
  feedType: 'POST_ORDER_FULFILLMENT_DATA',
  createdTime: '2021-02-28T12:14:25+00:00',
  processingStartTime: '2021-02-28T12:14:31+00:00',
  resultFeedDocumentId: 'amzn1.tortuga.3.9690c3e4-802b-4baa-8b62-XXX...'
}
```

but when I use the `resultFeedDocumentId`  for the `getFeedDocument` call - I get the same response as for `createFeedDocument`

**Comment by amz-tools** [comment]
Hi @unterweltler,

haven't tried the POST_ORDER_FULFILLMENT_DATA feed yet but I would say your feed xml looks right on first sight. One guess only: Although the FulfillmentDate should be ok in the format you provided you could try adding the timezone as well.

What I'm wondering is why the getFeedDocument call is not working. This should give you the download details to use with the .download() function in order to see the result of the feed processing (including error information).

This is how it should usually work:
```
let feed_document_details = await sellingPartner.callAPI({
    operation:'getFeedDocument',
    path:{
      feedDocumentId:'amzn1.tortuga.3.9690c3e4-802b-4baa-8b62-XXX...'
    }
});
let res = await sellingPartner.download(feed_document_details, {json:true});
```

**Comment by unterweltler** [comment]
Hey @amz-tools,

got it working - added the Zimezone `z` to the `FulfillmentDate` - in fact I'm doing `new Date().toIsoString()` to get the needed DateTime String.

I also managed to add multiple `Message` items to confirm multiple Orders in one Feed 👍 

I also now see the Feed Report - I just forgot to download it with the `.download()` method 🙈

**Comment by ameer8f26** [comment]
hey I am stuck into similar situation. I need to know the list of shipping services, and also need the fulfillment date format that you used.

**Comment by unterweltler** [comment]
@ameer8f26 
here is the [Schema](https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/OrderFulfillment.xsd) for the OrderFulfillment Feed

The CarrierCode can be found in the [Base Schema](https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/amzn-base.xsd) -> search for "CarrierCode"

The FulfillmentDate format needs to be a ISO_8601 encodes string - I'm using `new Date().toISOString()` to generate it at the moment where I generate the Feed.

**Comment by Ishthi** [comment]
Can anyone help me with C# or PHP code for POST_FLAT_FILE_FULFILLMENT_DATA example or guide, please?

**Comment by amz-tools** [comment]
Hi @Ishthi,

have you tried your luck asking the people using a PHP client for the API? I would guess there will be somebody around who can help:
[PHP Client](https://github.com/clousale/amazon-sp-api-php)
[C# Client](https://github.com/cafeasp/Selling-Partner-API)

**Comment by Ishthi** [comment]
Thanks for the prompt reply, I was using your c# library, the problem with your code is, there is no way to get STS tokens done because it uses completely different signing methods and headers (only a few changes). So I had to replicate the existing functions and modify them a little bit in order to work with STS token process and now it is working. I mean, I was able to get the STS token, and tried to download the order and it gives the expected outcome, I wanted to do a tracking update using  POST_FLAT_FILE_FULFILLMENT_DATA but I couldn't find any resources helpful outside.

I was able to make the STS part for your C# library by studying a PHP library that was converted from a node.js code.

So far no help for file uploading for tracking/order fulfillment xml file.

If you wish I can share the C# modified code

**Comment by amz-tools** [comment]
@Ishthi The C# client is maintained by other developers, at least for our team I can say we are not very experienced in C#, so wouldn't be of great help. But as said, I would suggest you open up an issue directly with the C# client guys and share the code with them.

**Comment by Ishthi** [comment]
I think I read the php documentation from https://github.com/clousale/amazon-sp-api-php/blob/master/README.md
If we enter role arn at the developer profile, no need ot STS token work, instead if we enter iam arn, we need to use STS intermediate token, is my understanding correct?

**Comment by amz-tools** [comment]
> I think I read the php documentation from https://github.com/clousale/amazon-sp-api-php/blob/master/README.md
> If we enter role arn at the developer profile, no need ot STS token work, instead if we enter iam arn, we need to use STS intermediate token, is my understanding correct?

Thats how I would understand it, too. But thats quite new to me that this might work. The SP Developer Guide is not mentioning that, it clearly states to use the role arn, which definetly requires an STS token to work.

**Comment by Ishthi** [comment]
I have given User ARN but it still works with STS token, means the otherway around

**Comment by Ishthi** [comment]
I was able to get the STS token and call to /feeds/2020-09-04/documents. From the developer portal it is clearly mentioned that this /feeds/2020-09-04/documents operation is allowed. So far Iw as able to get STS token while the application is in beta bersion which is in draft mode. When I make create feed call, it gives response as 
Forbidden

{
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}

What could be the reason?
Is this because the application is in Draft mode or any other hints?

**Comment by Ishthi** [comment]
If anyone can confirm say that, whether or not the app is in the draft mode, it still works, much appreciated.
Thanks

**Comment by amz-tools** [comment]
@Ishthi It should work fine in draft mode. There have been others with similar issues, see for example this discussion: https://github.com/amz-tools/amazon-sp-api/issues/34

**Comment by Ishthi** [comment]
I think the app should be self authorized to work in draft mode, am I correct?

**Comment by Ishthi** [comment]
Ok, after a long struggle here is my conclusion and finding. Each point are interrelated so carefully read

- When you create your app, you have an option to enter IAM ARN, if you give User ARN, you canuses your permanent AWS Access Key and AWS Secret Key for API calls. If you hav given Role ARN, you have to use STS token approach and get temporary keys and add additional headerfor API request x-amz-security-token

- For the website workflow approach to check whether your OAuth process working fine, you can keep the application in draft mode and test but, DON'T TRY TO CALL THE API. Otherwise you will get unauthorized access error.

- You must publish the app to amazon and get it approved for public use.

- In order to prevent this 401/Unauthorized error, self-authorize your app and call the API. Doing this helps to check all your API works working fine if you are trying to do a publicly accessible app (or for your own use)

**Comment by Anuj4444** [comment]
Hello 
I am trying to upload CSV file or TSV file to upload multiple Order Fulfilment Data in Python,
I am getting following error


I checked all headers multiple time they are all fine but still getting same error
"""""
original-record-number  order-id        order-item-id   error-code      error-type      error-message
0                       90061   Warning The --c96f8abfb2292d0ecaacb5ffdb48d64e field heading is invalid, so values in this field were ignored. To correct this error, download the template again and use the new copy, or fix the field heading in your existing file.
9223372036854775807                     50001   Error   The XML you submitted is ill-formed at the Amazon Envelope XML level at (or near) line 8, column 18.  

"""""

Can anyone suggest What am I doing wrong? and What else I can do in it?
Is it even possible to upload feed in CSV file in python by using requests library?
I can do it manually on seller central website.

**Comment by RizzoRat** [comment]
Erm... looks like you're using POST_ORDER_FULFILLEMT_DATA with a csv, but it's for XML ;-) If you really want to use CSV you rather should go with POST_FLAT_FILE_FULFILLMENT_DATA

**Comment by coder771** [comment]
> @ameer8f26 here is the [Schema](https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/OrderFulfillment.xsd) for the OrderFulfillment Feed
> 
> The CarrierCode can be found in the [Base Schema](https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/amzn-base.xsd) -> search for "CarrierCode"
> 
> The FulfillmentDate format needs to be a ISO_8601 encodes string - I'm using `new Date().toISOString()` to generate it at the moment where I generate the Feed.

@unterweltler do you have any link to amazon docs where it says fulfillment date needs to be iso_8601 formatted string?
