### ISSUE TITLE
Problems with getOrderMetrics passing an array to marketplaceIds

### ISSUE THREAD

**Issue by danieletdg** [amz-tools/amazon-sp-api#27]
Hello,
I'm trying to testing get ordermetrics, everything's gone well till i use an array of strings for marketplaceIds parametrer.

This is the req_params:
`{
    operation: 'getOrderMetrics',
    query: {
        granularity: 'Total',
        interval: '2021-03-31T00:00:00-07:00--2021-03-31T23:59:59-07:00',
        marketplaceIds: [
           'A13V1IB3VIYZZH',
           'A1F83G8C2ARO7P',
           'A1PA6795UKMFR9',
           'A1RKKUPIHCS9HS',
           'APJ6JRA9NG5V4'
        ]
    },
    method: 'GET',
    api_path: '/sales/v1/orderMetrics',
    restore_rate: 2
}
`

and this is the error:
`CustomError: Invalid Input
     at SellingPartner.callAPI (/var/www/djs-app/node_modules/amazon-sp-api/lib/SellingPartner.js:368:13)
     at processTicksAndRejections (internal/process/task_queues.js:93:5) {
     code: 'InvalidInput',
     details: '',
     type: 'error'
}
`
I don't understand why it works with marketplaceIds: ['APJ6JRA9NG5V4'] and not with marketplaceIds: ['A13V1IB3VIYZZH','A1F83G8C2ARO7P','A1PA6795UKMFR9','A1RKKUPIHCS9HS','APJ6JRA9NG5V4']

Any ideas?
thank you so much

Daniele

**Comment by amz-tools** [comment]
Hi @danieletdg,

I can confirm receiving the same error. This has already been discussed [here](https://github.com/amzn/selling-partner-api-docs/issues/117). Although there's no definitive conclusion it seems as if the operation doesn't accept more than one marketplaceId.
Although its quite strange that the operation requires an array "marketplaceIds" instead of a string "marketplaceId" of only one is supported. Maybe Amazon will update the docs or fix the operation in a way that it supports multiple MarketplaceIds some time in the future, we'll see...

**Comment by danieletdg** [comment]
thank you @amz-tools!

**Comment by amz-tools** [comment]
Amazon has updated the docs and they state that even though the parameter is called `marketplaceIds` it only supports one marketplace, [see here](https://developer-docs.amazon.com/sp-api/docs/sales-api-v1-reference#parameters).

So I think we can close this issue as it won't be changed to multi marketplace support, but at least docs are correct now.
