### ISSUE TITLE
Order resources missing / in api_path

### ISSUE THREAD

**Issue by ShaunParsons** [amz-tools/amazon-sp-api#3]
All the resources found in here are missing a `/` at the start of the `api_path` - https://github.com/amz-tools/amazon-sp-api/blob/main/lib/resources/orders.js

This results in the following error:

```bash
Error: getaddrinfo ENOTFOUND sellingpartnerapi-eu.amazon.comorders
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'sellingpartnerapi-eu.amazon.comorders'
}

```

**Comment by amz-tools** [comment]
Hi,

thanks, apparently we have still quite some things and tests missing here. Just published the fix.

**Comment by ShaunParsons** [comment]
> Hi,
> 
> thanks, apparently we have still quite some things and tests missing here. Just published the fix.

Thanks for the quick fix.

Whats the plans for this repo? This appears to be the only node client at present for the sp-api, but I'm a bit cautious about adopting it for a few reasons:

1. Missing tests
1. There's a few obvious places that could use the [aws-sdk](https://www.npmjs.com/package/aws-sdk) (assuming the role for example).
1. It would be nice to be able to pass in an access token instead of a refresh_token
  * Likewise, being able to get the access_token

**Comment by amz-tools** [comment]
> > Hi,
> > thanks, apparently we have still quite some things and tests missing here. Just published the fix.
> 
> Thanks for the quick fix.
> 
> Whats the plans for this repo? This appears to be the only node client at present for the sp-api, but I'm a bit cautious about adopting it for a few reasons:
> 
> 1. Missing tests
> 2. There's a few obvious places that could use the [aws-sdk](https://www.npmjs.com/package/aws-sdk) (assuming the role for example).
> 3. It would be nice to be able to pass in an `access_token` instead of a `refresh_token`
>    
>    * Likewise, being able to get the access_token

Good question. Published the repo basically because it was quite a pain to get the API running and we thought it would be nice to give others a head start. Definetly planning to keep working on it, but no concrete plans as to how and when, although I hope, as what is your 1st point, we can include at least some basic testing soon. 

To your 2nd point: We thought about using it but decided against it as we wanted to keep it lightweight and the functionality we need from aws-sdk is very limited. Also planning to drop crypto-js dependency in favor of node's standard crypto.

To your 3rd point: Its actually possible already. You can pass your access_token and your role_credentials inside the config options. There's also a getter for the access_token as well as the role_credentials, [see here in the docs](https://github.com/amz-tools/amazon-sp-api#config-params).
