### ISSUE TITLE
CORS Error When Testing 

### ISSUE THREAD

**Issue by cdmvfx** [amz-tools/amazon-sp-api#66]
Hi, I'm a novice developer so I apologize if this is a silly question!

I've gone through the whole setup of getting all the configuration right, finally got all the required tokens, and now I am facing this issue when using the example API call:

`Access to fetch at 'https://sellingpartnerapi-na.amazon.com/sellers/v1/marketplaceParticipations' from origin '<NGROK URL>' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Any idea why this is happening? I'm sure the authentication and signing is correct, otherwise it wouldn't try to make the request right? I understand what CORS is for, but if this is for an API call why CORS affecting it at all?

Any help is greatly appreciated!

Edit: For reference this is on a React / Next.JS app.

**Comment by amz-tools** [comment]
Hi @cdmvfx,

when you are trying to call the SP-API via a browser the request is blocked due to CORS as Amazon doesn't seem to allow CORS requests, as the error you mentioned states:

> No 'Access-Control-Allow-Origin' header is present

You should probably make requests to the API on the serverside and only pass the necessary result data to your frontend.
