### ISSUE TITLE
_constructEncodedQueryString replacing whitespace with '+' causes issues with searchCatalogItems

### ISSUE THREAD

**Issue by callumb123** [amz-tools/amazon-sp-api#70]
I see a change was made to _constructEncodedQueryString to resolve ( #63 ) so that whitespace in the query string is now replaced with a '+'. It seems this is causing searchCatalogItems (2020-12-01) to return zero results.

Example: 
If I call searchCatalogItems in version 0.6.2 with the query string: "Castor 1 Pack" it is encoded to "Castor%2B1%2BPack" which returns zero items/results.

If I comment out the below encoding
`  
encoder:(str) => {
    return encodeURIComponent(str.replace(/ /g, '+'));
}`
it is encoded to "Castor%201%20Pack" which returns 87029 items/results.

I have not created a pull request as I do not fully understand the reason for the initial change but if you let me know I would be happy to do so.

**Comment by amz-tools** [comment]
@callumb123,

thanks a lot for noticing the bug! Tests for version 0.6.2 passed without any problems since the `searchCatalogItems` spec didn't include whitespace for `keywords` (changed that now to be safe in the future).

To the bug itself: Apparently the whitespace issue discussed in #63 only exists for SKUs. So for now we have changed the `_constructEncodedQueryString` to only replace whitespace with `+` sign for SKU keys (until there is a fix by Amazon or any other fix that will make this obsolete).
