### ISSUE TITLE
How to use Sandbox for Feed API ?

### ISSUE THREAD

**Issue by ghoshak-rakheshdhevaraj** [amz-tools/amazon-sp-api#88]
I am trying to upload feed for grocery segment using sandbox. when i enabled use_sandbox to true. I get following error 

 **Cannot read property '0' of undefined**

Please help me how to use sandbox for post data. Any example would be helpful for me to understand.

**Comment by amz-tools** [comment]
Hi @ghoshak-rakheshdhevaraj,

for the sandbox you have to use the correct static sandbox parameters. You can find them inside the [api model definitions](https://github.com/amzn/selling-partner-api-models/tree/main/models).

For the feed endpoint take a look at [this json file](https://github.com/amzn/selling-partner-api-models/blob/main/models/feeds-api-model/feeds_2021-06-30.json) and search for the `x-amzn-api-sandbox` keys.

I can see our module docs are a bit outdated on that since it says its called `x-amazon-spds-sandbox-behaviors`, which is apparently not correct anymore. Will try to update the docs asap.

For more info on sandbox behaviour you may take a look at [the corresponding section in the SP API Dev Guide](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#how-to-make-a-sandbox-call-to-the-selling-partner-api).

**Comment by amz-tools** [comment]
Docs updated accordingly in version 0.6.6.
